name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install puppeteer

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rust-version: stable

      - name: Install dependencies
        run: |
          cargo install hxn

      - name: Start the docs server
        run: |
          npx live-server docs &
          sleep 2

      - name: Generate URLs
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto('http://localhost:8080');
            const numberOfPages = await page.evaluate(() => {
              return document.querySelectorAll('.remark-slide').length;
            });
            const urls = Array.from({ length: numberOfPages }, (_, i) => \`http://localhost:8080/#\${i + 1}\`).join('\\n');
            require('fs').writeFileSync('urls.txt', urls);
            await browser.close();
          })();"

      - name: Run hxn on URLs
        run: |
          while IFS= read -r url; do
            hxn -b "/usr/bin/google-chrome" -u "$url"
          done < urls.txt

      - name: List hxnshots directory
        run: |
          # Print filenames in hxnshots directory
          echo "Files in hxnshots directory:"
          ls -l hxnshots      
